import { DiscountButton } from "./../components/SharedComponents/UI/Buttons/DiscountButton";
import { AddToCart } from "./../components/SharedComponents/UI/Buttons/AddToCart";
import "./globals.css";
import { Inter, Poppins } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import ReduxProvider from "@/components/ReduxProvider/ReduxProvider";
import Navbar from "@/components/SharedComponents/Navbar/Navbar";
import Footer from "@/components/SharedComponents/Footer/Footer";

export const metadata = {
  title: "Concepteur Fashion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <script
        async
        src="https://kit.fontawesome.com/a7908c27f8.js"
        crossorigin="anonymous"
        strategy="lazyOnload"
      ></script>

      <body className={inter.className}>
        <ReduxProvider>
          <Navbar />
          {children}
          <DiscountButton />
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
