import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import ReduxProvider from "@/components/ReduxProvider/ReduxProvider";
import Navbar from "@/components/SharedComponents/Navbar/Navbar";
import Footer from "@/components/SharedComponents/Footer/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Navbar />
          {children}
          
          <Footer/>
        </ReduxProvider>
      </body>
    </html>
  );
}
